apiVersion: v1
kind: Service
metadata:
  name: ip-api
  namespace: web
spec:
  type: NodePort
  selector:
    app: ip-api
  ports:
    - name: http
      port: 8066
      targetPort: 5000
      nodePort: 30080

